In [42]:
%matplotlib inline
import math
import numpy as np
import pandas as pd
from IPython.display import display
import scipy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
import os
from statsmodels.sandbox.regression.predstd import wls_prediction_std
from sklearn import linear_model
import statsmodels.formula.api as smf
from sklearn.metrics import confusion_matrix

os.getcwd()
os.chdir('/Users/kylehoward/desktop/thinkful/thinkful-2') 
os.getcwd()

'/Users/kylehoward/Desktop/Thinkful/Thinkful-2'

In [43]:
data = ("FBI_data_4.csv")
fbi = pd.read_csv(data, usecols=[1,2,3,6,8,11,12])
fbi.columns = ['population', 'violent_crime', 'murder', 'robbery', 'prop_crime', 'gta', 'arsen']
fbi = fbi.replace([np.inf, -np.inf], np.nan).dropna()
fbi = fbi[1:]
fbi = fbi.dropna()




In [44]:
fbi['population'] = fbi['population'].astype(int)
fbi['population_squared'] = fbi['population'] * fbi['population']
fbi['population_squared'].head(10)

1         6640929
2         8099716
6         3171961
7     13993943616
8        90611361
9       330585124
10        4214809
11       20457529
12         432964
13        6360484
Name: population_squared, dtype: int64

In [45]:

fbi['population_sqrt'] = fbi['population'] ** .5
fbi['population_sqrt'] = fbi['population_sqrt'].astype(int)
fbi['population_sqrt'].head(100)

1       50
2       53
6       42
7      343
8       97
9      134
10      45
11      67
12      25
13      50
16      86
17      73
19      75
23      37
25      31
26      48
27      45
28      45
29      48
30      89
33      79
34      34
38      47
39     155
42      47
44      27
45     185
46      59
48      31
51      42
      ... 
125     52
128     39
134    213
135     97
136     25
138     89
139    192
140    234
141     87
142     62
143     57
146     81
149     37
150    146
153     80
157     36
158    123
159    115
160     71
161    153
163    134
164     49
167    190
173     48
174     60
175    103
182     76
183     92
184    110
185    138
Name: population_sqrt, Length: 100, dtype: int64

In [46]:
fbi['murder'] = fbi['murder'].astype(int)
fbi['has_murder'] = np.where(fbi['murder']>=1, 1, 0)
fbi['has_murder'].head(10)

1     0
2     0
6     0
7     1
8     0
9     0
10    0
11    0
12    0
13    0
Name: has_murder, dtype: int64

In [47]:
fbi['robbery'] = fbi['robbery'].astype(int)
fbi['has_robbery'] = np.where(fbi['robbery']>=1, 1, 0)
fbi['arsen'] = fbi['arsen'].astype(int)
fbi['has_robbery'].head(10)

1     0
2     0
6     0
7     1
8     1
9     1
10    0
11    1
12    0
13    0
Name: has_robbery, dtype: int64

In [48]:
# Why is my analysis still being blocked by the integer error
regr = linear_model.LinearRegression()
fbi['prop_crime'].astype(int)
fbi['population_sqrt'].astype(int)
fbi['violent_crime'].astype(int)
fbi['arsen'].astype(int)
fbi['gta'].astype(int)

#fbi['prop_crime'] = pd.to_numeric(fbi['prop_crime'], errors='coerce')
#fbi['gta'] = pd.to_numeric(fbi['gta'], errors='coerce')
#fbi['violent_crime'] = pd.to_numeric(fbi['violent_crime'], errors='coerce')
#fbi['arsen'] = pd.to_numeric(fbi['arsen'], errors='coerce')
Y = fbi['prop_crime'].values.reshape(-1, 1)
X = fbi[['gta', 'population_sqrt', 'violent_crime', 'arsen']]
X_training = X[:100]
Y_training = Y[:100]
X_test = X[100:]
Y_test = Y[100:]
regr.fit(X_training, Y_training)
y_pred_test = regr.predict(X_test)
fbi.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 186 entries, 1 to 346
Data columns (total 11 columns):
population            186 non-null int64
violent_crime         186 non-null int64
murder                186 non-null int64
robbery               186 non-null int64
prop_crime            186 non-null int64
gta                   186 non-null int64
arsen                 186 non-null int64
population_squared    186 non-null int64
population_sqrt       186 non-null int64
has_murder            186 non-null int64
has_robbery           186 non-null int64
dtypes: int64(11)
memory usage: 17.4 KB


In [49]:
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X_training, Y_training))


Coefficients: 
 [[ 17.30987145   4.02844667  -3.45162097  21.30677974]]

Intercept: 
 [-208.19966493]

R-squared:
0.781025167054


In [50]:
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X_test, Y_test))


Coefficients: 
 [[ 17.30987145   4.02844667  -3.45162097  21.30677974]]

Intercept: 
 [-208.19966493]

R-squared:
0.916290908524


In [51]:
print('Coefficients: \n', regr.coef_)
print(sklearn.metrics.mean_squared_error(Y_test, y_pred_test))
print(sklearn.metrics.r2_score(Y_test, y_pred_test))

Coefficients: 
 [[ 17.30987145   4.02844667  -3.45162097  21.30677974]]
148324.714285
0.916290908524


In [52]:
print(fbi.violent_crime)

1         3
2         3
6         3
7       107
8         9
9        30
10        0
11        5
12        0
13        2
16        5
17        8
19       15
23        0
25        1
26        2
27        1
28        4
29        0
30        1
33        0
34        0
38        5
39       14
42        3
44        0
45       10
46        0
48        0
51        3
       ... 
283      15
287       0
292       3
293       1
295       0
297       0
298       8
300      19
301      44
306       1
309       9
310    1192
311       6
313      34
314     118
315     371
317       0
319       0
324      40
326       6
327       2
328       4
335       0
336      11
337       2
338      35
341       4
342       0
344       7
346    1036
Name: violent_crime, Length: 186, dtype: int64


In [79]:
linear_formula = 'prop_crime ~ gta+population_sqrt+violent_crime+arsen'
lm = smf.ols(formula=linear_formula, data=fbi).fit()

In [80]:
lm.params

Intercept         -178.889203
gta                 11.623850
population_sqrt      3.652602
violent_crime       -1.546253
arsen               38.042049
dtype: float64

In [81]:
lm.pvalues

Intercept          1.137841e-08
gta                1.108854e-10
population_sqrt    5.795206e-24
violent_crime      1.491665e-04
arsen              3.553459e-16
dtype: float64

In [82]:
lm.rsquared

0.95833936944267883

In [83]:
lm.conf_int()

0           1
Intercept       -237.870404 -119.908001
gta                8.276037   14.971663
population_sqrt    3.037564    4.267639
violent_crime     -2.333693   -0.758813
arsen             29.679695   46.404403