In [1]:
%matplotlib inline
import math
import numpy as np
import pandas as pd
from IPython.display import display
import scipy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
import os
from statsmodels.sandbox.regression.predstd import wls_prediction_std
from sklearn import linear_model
import statsmodels.formula.api as smf
from sklearn.metrics import confusion_matrix
os.getcwd()
os.chdir('/Users/kylehoward/desktop/thinkful/thinkful-2') 
os.getcwd()

'/Users/kylehoward/Desktop/Thinkful/Thinkful-2'

In [2]:
data_path = ("FBI_data_4.csv")
fbi = pd.read_csv(data_path, usecols=[1,2,3,6,8,11,12])
fbi.columns = ['population', 'violent_crime', 'murder', 'robbery', 'prop_crime', 'gta', 'arsen']
fbi = fbi.replace([np.inf, -np.inf], np.nan).dropna()
fbi = fbi[1:]
#fbi = fbi.dropna()
fbi.head(186)

population  violent_crime  murder  robbery  prop_crime  gta  arsen
1          2577              3       0        0          24    1    0.0
2          2846              3       0        0          16    0    0.0
6          1781              3       0        0          10    0    0.0
7        118296            107       1       31        2118   32    3.0
8          9519              9       0        4         210    6    1.0
9         18182             30       0       12         405   15    0.0
10         2053              0       0        0          39    1    0.0
11         4523              5       0        3          33    1    0.0
12          658              0       0        0           2    0    0.0
13         2522              2       0        0           5    1    0.0
16         7473              5       0        1          88    1    0.0
17         5418              8       0        3          94    0    1.0
19         5733             15       0        3         191    2    2.0
23         1410              0       0        0          14    0    0.0
25         1022              1       0        0           4    0    0.0
26         2325              2       0        0          24    0    0.0
27         2054              1       0        0          20    0    0.0
28         2065              4       0        1          31    2    0.0
29         2358              0       0        0          13    0    0.0
30         7976              1       0        0          11    0    0.0
33         6390              0       0        0          47    3    0.0
34         1174              0       0        0          10    0    0.0
38         2219              5       0        0          46    0    0.0
39        24165             14       0        0         348    5    1.0
42         2246              3       0        1          12    0    0.0
44          762              0       0        0           2    0    0.0
45        34462             10       0        0         198    9    1.0
46         3481              0       0        0           8    0    0.0
48          980              0       0        0           4    0    0.0
51         1835              3       0        2          53    2    0.0
..          ...            ...     ...      ...         ...  ...    ...
283       19318             15       0        5         319    0    0.0
287         872              0       0        0           0    0    0.0
292        2412              3       0        0          41    0    0.0
293        1351              1       0        0          15    0    0.0
295        1437              0       0        0           0    0    0.0
297        2450              0       0        0          10    0    0.0
298        9996              8       1        1          58    2    0.0
300        6487             19       0        6         186    6    0.0
301       50603             44       0       16        1020   49    1.0
306        6587              1       0        0          24    2    1.0
309       10886              9       0        1          60    1    0.0
310      143834           1192      21      400        6473  394   57.0
311       11449              6       0        3         110    4    0.0
313       14987             34       0        4         315    2    4.0
314       58082            118       1       26        1099   27    1.0
315       49898            371       1      145        1985   87    5.0
317        6578              0       0        0          35    1    0.0
319         615              0       0        0           0    0    0.0
324       27940             40       0       16         767   26    1.0
326        3453              6       0        0          78    0    0.0
327        5828              2       0        1          58    2    0.0
328        8392              4       0        0          59    1    0.0
335        1797              0       0        0          25    0    0.0
336        4574             11       0       

In [3]:
fbi['population'] = fbi['population'].astype(int)
fbi['population_squared'] = fbi['population'] * fbi['population']
fbi['population_squared'].head(10)

1         6640929
2         8099716
6         3171961
7     13993943616
8        90611361
9       330585124
10        4214809
11       20457529
12         432964
13        6360484
Name: population_squared, dtype: int64

In [4]:

fbi['population_sqrt'] = fbi['population'] ** .5
fbi['population_sqrt'].head(10)

1      50.764161
2      53.347915
6      42.201896
7     343.941856
8      97.565363
9     134.840647
10     45.310043
11     67.253253
12     25.651511
13     50.219518
Name: population_sqrt, dtype: float64

In [5]:
fbi['murder'] = fbi['murder'].astype(int)
fbi['has_murder'] = np.where(fbi['murder']>=1, 1, 0)
fbi['has_murder'].head(10)

1     0
2     0
6     0
7     1
8     0
9     0
10    0
11    0
12    0
13    0
Name: has_murder, dtype: int64

In [6]:
fbi['robbery'] = fbi['robbery'].astype(int)
fbi['has_robbery'] = np.where(fbi['robbery']>=1, 1, 0)
fbi['has_robbery'].head(10)

1     0
2     0
6     0
7     1
8     1
9     1
10    0
11    1
12    0
13    0
Name: has_robbery, dtype: int64

In [7]:
regr = linear_model.LinearRegression()
fbi['prop_crime'] = fbi['prop_crime'].astype(int)
fbi['population_sqrt'] = fbi['population_sqrt'].astype(int)
fbi['violent_crime'] = fbi['violent_crime'].astype(int)
fbi['arsen'] = fbi['arsen'].astype(int)
fbi['gta'] = fbi['gta'].astype(int)
Y = fbi['prop_crime'].values.reshape(-1, 1)
X = fbi[['gta', 'population_sqrt', 'violent_crime', 'arsen']]
X_training = X[:100]
Y_training = Y[:100]
X_test = X[100:]
Y_test = Y[100:]
regr.fit(X_training, Y_training)
y_pred_test = regr.predict(X_test)
fbi['gta'].describe()

count    186.000000
mean      13.989247
std       57.506191
min        0.000000
25%        0.000000
50%        2.000000
75%        5.000000
max      609.000000
Name: gta, dtype: float64

In [8]:
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X_training, Y_training))


Coefficients: 
 [[ 17.30987145   4.02844667  -3.45162097  21.30677974]]

Intercept: 
 [-208.19966493]

R-squared:
0.781025167054


In [9]:
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X_test, Y_test))


Coefficients: 
 [[ 17.30987145   4.02844667  -3.45162097  21.30677974]]

Intercept: 
 [-208.19966493]

R-squared:
0.916290908524


In [10]:
print('Coefficients: \n', regr.coef_)
print(sklearn.metrics.mean_squared_error(Y_test, y_pred_test))
print(sklearn.metrics.r2_score(Y_test, y_pred_test))

Coefficients: 
 [[ 17.30987145   4.02844667  -3.45162097  21.30677974]]
148324.714285
0.916290908524


In [11]:
plt.scatter(fbi['gta'], Y,  color='black')
plt.xlim(0,1000)
plt.ylim(0,14000)
plt.loglog()
plt.show()

/Users/kylehoward/anaconda/envs/P3/lib/python3.6/site-packages/matplotlib/transforms.py:383: RuntimeWarning: invalid value encountered in double_scalars
  return points[1, 0] - points[0, 0]


OverflowError: cannot convert float infinity to integer