In [14]:
from sklearn.model_selection import cross_val_score
from sklearn import neighbors
import pandas as pd
import numpy as np
import scipy
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats
import os
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import StratifiedKFold
from statsmodels.sandbox.regression.predstd import wls_prediction_std
from sklearn import linear_model
import seaborn as sns
import statsmodels.formula.api as smf
from IPython.display import display
import sklearn
import math
os.getcwd()
os.chdir('/Users/kylehoward/desktop/thinkful/thinkful-2') 
os.getcwd()


'/Users/kylehoward/Desktop/Thinkful/Thinkful-2'

In [4]:
df = pd.DataFrame(pd.read_csv('NBA_Thinkful_unit_1.2.csv'))

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 28 columns):
data_set    116 non-null object
date        116 non-null object
player      116 non-null object
pos         116 non-null object
team        116 non-null object
opp         116 non-null object
venue       116 non-null object
min         116 non-null float64
fg          116 non-null int64
fga         116 non-null int64
3p          116 non-null int64
3pa         116 non-null int64
ft          116 non-null int64
fta         116 non-null int64
oreb        116 non-null int64
dreb        116 non-null int64
reb         116 non-null int64
assist      116 non-null int64
pf          116 non-null int64
st          116 non-null int64
to          116 non-null int64
bl          116 non-null int64
pts         116 non-null int64
double      116 non-null int64
triple      116 non-null int64
dk          116 non-null float64
fd          116 non-null float64
yh          116 non-null float64
dtypes: floa

In [6]:
''' Figure out features for this'''
knn = neighbors.KNeighborsRegressor(n_neighbors=10)
df['dk'].astype(int)
df['fd'].astype(int)
df['yh'].astype(int)
#fbi['gta'].astype(int)
Y = df['dk'].values.reshape(-1, 1)
X = df[['min', 'pts']]
X_training = X[:100]
Y_training = Y[:100]
X_test = X[100:]
Y_test = Y[100:]
knn.fit(X_training, Y_training)
y_pred_test = knn.predict(X_test)
#fbi['prop_crime'].describe

In [9]:
score = cross_val_score(knn, X, Y, cv=5)
print(knn.score(X_training, Y_training))
print(score)

0.880526609538
[ 0.8176732   0.83873892  0.80296164  0.89670985  0.93860818]


In [ ]:
from sklearn.model_selection import cross_val_score
2
score = cross_val_score(knn, X, Y, cv=5)
3
print("Unweighted Accuracy: %0.2f (+/- %0.2f)" % (score.mean(), score.std() * 2))
4
score_w = cross_val_score(knn_w, X, Y, cv=5)
5
print("Weighted Accuracy: %0.2f (+/- %0.2f)" % (score_w.mean(), score_w.std() * 2))

In [10]:
''' Figure out features for this'''
regr = linear_model.LinearRegression()
df['dk'].astype(int)
df['fd'].astype(int)
df['yh'].astype(int)
#fbi['gta'].astype(int)
Y = df['dk'].values.reshape(-1, 1)
X = df[['min', 'pts']]
X_training = X[:100]
Y_training = Y[:100]
X_test = X[100:]
Y_test = Y[100:]
regr.fit(X_training, Y_training)
y_pred_test = regr.predict(X_test)
#fbi['prop_crime'].describe

In [11]:
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X_training, Y_training))


Coefficients: 
 [[ 0.40324489  1.15299655]]

Intercept: 
 [-0.00828271]

R-squared:
0.890711705857


In [12]:
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X_test, Y_test))


Coefficients: 
 [[ 0.40324489  1.15299655]]

Intercept: 
 [-0.00828271]

R-squared:
0.951185795344


In [16]:
print('Coefficients: \n', regr.coef_)
print(sklearn.metrics.mean_squared_error(Y_test, y_pred_test))
print(sklearn.metrics.r2_score(Y_test, y_pred_test))

Coefficients: 
 [[ 0.40324489  1.15299655]]
13.3028241713
0.951185795344


In [18]:
linear_formula = 'dk ~ min+pts'
lm = smf.ols(formula=linear_formula, data=df).fit()

In [19]:
lm.params

Intercept    0.084470
min          0.383639
pts          1.173034
dtype: float64

In [20]:
lm.pvalues

Intercept    9.320513e-01
min          2.589501e-09
pts          2.197577e-31
dtype: float64

In [21]:
lm.rsquared

0.90065021311246996

In [22]:
lm.conf_int()

0         1
Intercept -1.873895  2.042836
min        0.266189  0.501088
pts        1.030184  1.315884