In [26]:
from sklearn.model_selection import cross_val_score
from sklearn import neighbors
import pandas as pd
import numpy as np
import scipy
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats
import os
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import StratifiedKFold
from statsmodels.sandbox.regression.predstd import wls_prediction_std
from sklearn import linear_model
import seaborn as sns
import statsmodels.formula.api as smf
from IPython.display import display
import sklearn
import math
os.getcwd()
os.chdir('/Users/kylehoward/desktop/thinkful/thinkful-2') 
os.getcwd()


'/Users/kylehoward/Desktop/Thinkful/Thinkful-2'

In [27]:
df = pd.DataFrame(pd.read_csv('NBA_Thinkful_unit_1.2.csv'))

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 28 columns):
data_set    116 non-null object
date        116 non-null object
player      116 non-null object
pos         116 non-null object
team        116 non-null object
opp         116 non-null object
venue       116 non-null object
min         116 non-null float64
fg          116 non-null int64
fga         116 non-null int64
3p          116 non-null int64
3pa         116 non-null int64
ft          116 non-null int64
fta         116 non-null int64
oreb        116 non-null int64
dreb        116 non-null int64
reb         116 non-null int64
assist      116 non-null int64
pf          116 non-null int64
st          116 non-null int64
to          116 non-null int64
bl          116 non-null int64
pts         116 non-null int64
double      116 non-null int64
triple      116 non-null int64
dk          116 non-null float64
fd          116 non-null float64
yh          116 non-null float64
dtypes: floa

In [64]:
''' Figure out features for this'''
knn = neighbors.KNeighborsRegressor(n_neighbors=10)
df['dk'].astype(int)
df['fd'].astype(int)
df['yh'].astype(int)

Y = df['dk'].values.reshape(-1, 1)
X = df[['min', 'pts', 'reb']]
X_training = X[:68]
Y_training = Y[:68]
X_test = X[68:]
Y_test = Y[68:]
knn.fit(X_training, Y_training)
y_pred_test = knn.predict(X_test)


In [65]:
score = cross_val_score(knn, X, Y, cv=5)
print(knn.score(X_training, Y_training))
print(score)

0.896721167128
[ 0.87323048  0.9040855   0.81647546  0.91887886  0.95552891]


In [69]:
score = cross_val_score(knn, X_test, Y_test, cv=5)
print(knn.score(X_test, Y_test))
print(score)

0.923480494635
[ 0.86650883  0.7194902   0.94839713  0.89320773  0.87456834]


In [68]:
from sklearn.model_selection import cross_val_score
2
score = cross_val_score(knn, X_test, Y_test, cv=5)
3
print("Unweighted Accuracy: %0.2f (+/- %0.2f)" % (score.mean(), score.std() * 2))



Unweighted Accuracy: 0.86 (+/- 0.15)


In [44]:
''' Figure out features for this'''
regr = linear_model.LinearRegression()
df['dk'].astype(int)
df['fd'].astype(int)
df['yh'].astype(int)
#fbi['gta'].astype(int)
Y = df['dk'].values.reshape(-1, 1)
X = df[['min', 'pts', 'reb']]
X_training = X[:100]
Y_training = Y[:100]
X_test = X[100:]
Y_test = Y[100:]
regr.fit(X_training, Y_training)
y_pred_test = regr.predict(X_test)
print(y_pred_test)

[[  1.6772197 ]
 [  0.9189395 ]
 [  0.09077857]
 [  2.0795545 ]
 [  0.09821269]
 [  0.09821269]
 [ 28.1931113 ]
 [  3.02368769]
 [ 31.97403196]
 [ 18.76136109]
 [ 41.75066289]
 [ 41.21354394]
 [ 28.22470504]
 [ 17.70066115]
 [  2.24013148]
 [  0.09821269]]


In [45]:
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X_training, Y_training))


Coefficients: 
 [[ 0.14868239  1.12902126  1.51299227]]

Intercept: 
 [ 0.07591033]

R-squared:
0.949711925638


In [46]:
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X_test, Y_test))


Coefficients: 
 [[ 0.14868239  1.12902126  1.51299227]]

Intercept: 
 [ 0.07591033]

R-squared:
0.946983623462


In [47]:
print('Coefficients: \n', regr.coef_)
print(sklearn.metrics.mean_squared_error(Y_test, y_pred_test))
print(sklearn.metrics.r2_score(Y_test, y_pred_test))

Coefficients: 
 [[ 0.14868239  1.12902126  1.51299227]]
14.4479980828
0.946983623462


In [59]:
linear_formula = 'dk ~ min+pts+reb'
lm = smf.ols(formula=linear_formula, data=df).fit()

In [60]:
lm.params

Intercept    0.041461
min          0.154311
pts          1.145716
reb          1.455935
dtype: float64

In [61]:
lm.pvalues

Intercept    9.530472e-01
min          1.495890e-03
pts          4.741910e-43
reb          1.585195e-18
dtype: float64

In [62]:
lm.rsquared

0.95025495759596046

In [63]:
lm.conf_int()

0         1
Intercept -1.350620  1.433543
min        0.060404  0.248219
pts        1.044045  1.247387
reb        1.182967  1.728904